### ISSUE TITLE
QTPyLib 2.0 Library Structure

### ISSUE THREAD

**Issue by ranaroussi** [ranaroussi/qtpylib#138]
![qtpylib 2 0](https://user-images.githubusercontent.com/1185458/64073540-24791d80-cca8-11e9-86b7-32beef49451a.png)

**Comment by ranaroussi** [comment]
Instantiation would look something like this (pseudo code):

```python

from qtpylib.algo import Algo, Ticker

class TestStrategy(Algo):

    def on_bar(self):
        portfolio = self.tickers()

        bars = portfolio.get_bars(window=100)
        aapl.record(ma_cross=1, short_mavg=2, long_mavg=3)

        bars.assign('longma', bars["close"].rolling(50).mean())
        bars.assign('shortma', bars["close"].rolling(10).mean())

        signals = bars['shortma'] > bars['longma']

        qty = self.broker.allocate(signals, self.prices)
        self.broker.buy(qty, self.prices)


# run in backtest mode (using 2 stocks)

strategy = TestStrategy(
    config="algo.toml",
    """
    instruments = [
        # Ticker(<name>, <broker identifier>, <blotter identifier>), ie:
        Ticker("aapl", "AAPL.STK", "AAPL@NASDAQ"),
        Ticker("tsla", "TSLA.STK", "TSLA@NASDAQ"),
        ...
    ]

strategy.backtest(start="2018-01-01", end=None, data="csv://path/to/csv_directory")
```

**Comment by ranaroussi** [comment]
### Instantiation

Instantiate strategy and backtest it with 2 stocks (pseudo code):

```python
strategy = TestStrategy(
    config="algo.toml",
    instruments = [
        # Ticker(<name>, <broker identifier>, <blotter identifier>), ie:
        Ticker("aapl", "AAPL.STK", "AAPL@NASDAQ"),
        Ticker("tsla", "TSLA.STK", "TSLA@NASDAQ"),
        ...
    ]

strategy.backtest(start="2018-01-01", end=None, data="csv://path/to/csv_directory")
```

**Comment by ranaroussi** [comment]
```python
from qtpylib.pipeline import Universe

strategy = TestStrategy(
    config="algo.toml",
    instruments = Universe.SP500
]

strategy.run()
```

---

or, using a custom universe:

**1. Create universe class**

```python
# custom_universe.py

from qtpylib.pipline import Universe

class FavoriteTechStocks_IB_IQFeed(Universe):
    members = [
        Ticker("aapl", "AAPL.STK", "NFLX@NASDAQ")
        Ticker("goog", "GOOG.STK", "NFLX@NASDAQ")
        Ticker("amzn", "AMZN.STK", "NFLX@NASDAQ")
        Ticker("nflx", "NFLX.STK", "NFLX@NASDAQ")
    ]
```

**2. Use it in your algo**
```python

from custom_universe import FavoriteTechStocks_IB_IQFeed

strategy = TestStrategy(
    config="algo.toml",
    instruments = FavoriteTechStocks_IB_IQFeed
]

strategy.run()
```

**Comment by ranaroussi** [comment]
### Example of algo configuration:

```toml
# algo.toml

title = "Algo Configuration"
timezone = "US/Central"

[services]
datastore = "mysql://user:password@localhost:3306/qtpylib"
blotter = "tcp://192.168.1.29:55555:55556"
broker = "ibgw://127.0.0.1:4001/UXXXXXXX"

[sms]
provider = "nexmo"
phones = []

[backtest]
output = "~/backtests/"
data = "datastore"
cash = 1e6

  [backtest.commission]
   value = 0.001
   type = "percent"

  [backtest.slippage]
   value = 2
   type = "bps"

[events]
tick = 0
bars = "10T"
book = false

[history]
tick = 10
bars = 30
preload = true
futures = "continuous"

[schedule]
date_rules = "daily"
date_offset = 0
time_rules = "market"  # premarket, postmarket
time_offset = 0
calendar = "NYSE"
half_days = true

```
